ECHO off
SET SSCEXEPATH=%HDMTTOS%\Runtime\Release
REM Make it work on the Cart/HDE

%SSCEXEPATH%\SingleScriptCmd.exe setInstanceParam "TPI_MIXDETCT_XXX::CTRL_X_MIXDET_K_STARTPREPRL1_X_X_X_X_DLCPMIXDET" "BypassPort" 1
%SSCEXEPATH%\SingleScriptCmd.exe setInstanceParam "IPC::PTH_BGR_CXPKGS7::BGR_X_SCREEN_K_STARTANA0CPU_X_X_X_X_BGR_TEMPCO_CALC" "BypassPort" 1
%SSCEXEPATH%\SingleScriptCmd.exe setInstanceParam "IPC::PTH_BGR_CXPKGS7::BGR_X_GSDS2DFF_E_STARTANA0CPU_X_X_X_X_GSDS2DFFPR" "BypassPort" 1
%SSCEXEPATH%\SingleScriptCmd.exe setInstanceParam "IPC::PTH_BGR_CXPKGS7::BGR_X_ANADC_K_STARTANA0CPU_X_X_X_X_BGR_ANAPRB_POST" "BypassPort" 1

REM DFF NONKILL
%SSCEXEPATH%\SingleScriptCmd.exe setInstanceParam "TPI_DFF_XXX::DFFX_X_DFFREAD_K_STARTPREPRL1_X_X_X_X_DFFREAD" "EnabledModules" "NONKILL"
%SSCEXEPATH%\SingleScriptCmd.exe setInstanceParam "TPI_DFF_XXX::DFFX_X_DFFENDFLOW_K_FINAL_X_X_X_X_DFFVAL" "BypassPort" 1
%SSCEXEPATH%\SingleScriptCmd.exe setInstanceParam "PTH_CEP_HKPKGS7::CEP_X_SCREEN_E_BEGINHUBPKG_X_X_X_X_CEP_EVENT0_CALC" "BypassPort" 1
%SSCEXEPATH%\SingleScriptCmd.exe setInstanceParam "IPH::PTH_DTS_HXNVL::DTS_X_SCREEN_K_STARTANA0HUB_X_X_X_X_TEMPDELTA" "BypassPort" 1
