from pyqs import PortInject, ManualInject, SetModule, ctvData, portData, pinData, thermalData, userVar, triggerData, patternData

# Set the module for all tests
SetModule('IPC::FUN_ATOM_CXPKGS9')

# List of all test names from FUN_ATOM_CX816.mtpl
test_names = [
    "SBFT_X_VMIN_K_F5XAT_X_VCCIA_F5_X_F7_L2_DRAGON",
    "SBFT_X_VMIN_K_F5XAT_X_VCCIA_F5_X_F7_L2_LOCKSTEP",
    "SBFT_X_VMIN_K_F5XAT_X_VCCIA_F5_X_F7_BILBO",
    "SBFT_X_VMIN_K_F5XAT_X_VCCIA_F5_X_F7_TRUNKDBG",
    "SBFT_X_VMIN_K_F5XAT_X_VCCIA_F5_X_F7_SLC_DRAGON",
    "SBFT_X_VMIN_K_F5XAT_X_VCCIA_F5_X_F6_L2_DRAGON",
    "SBFT_X_VMIN_K_F5XAT_X_VCCIA_F5_X_F6_L2_LOCKSTEP",
    "SBFT_X_VMIN_K_F5XAT_X_VCCIA_F5_X_F6_BILBO",
    "SBFT_X_VMIN_K_F5XAT_X_VCCIA_F5_X_F6_TRUNKDBG",
    "SBFT_X_VMIN_K_F5XAT_X_VCCIA_F5_X_F6_SLC_DRAGON",
    "SBFT_X_VMIN_K_F5XAT_X_VCCIA_F5_X_F5_L2_DRAGON",
    "SBFT_X_VMIN_K_F5XAT_X_VCCIA_F5_X_F5_L2_LOCKSTEP",
    "SBFT_X_VMIN_K_F5XAT_X_VCCIA_F5_X_F5_BILBO",
    "SBFT_X_VMIN_K_F5XAT_X_VCCIA_F5_X_F5_TRUNKDBG",
    "SBFT_X_VMIN_K_F5XAT_X_VCCIA_F5_X_F5_SLC_DRAGON",
    "SBFT_X_VMIN_K_F1XAT_X_VCCIA_F1_X_1200_L2_DRAGON",
    "SBFT_X_VMIN_K_F1XAT_X_VCCIA_F1_X_1200_L2_LOCKSTEP",
    "SBFT_X_VMIN_K_F1XAT_X_VCCIA_F1_X_1200_BILBO",
    "SBFT_X_VMIN_K_F1XAT_X_VCCIA_F1_X_1200_TRUNKDBG",
    "SBFT_X_VMIN_K_F1XAT_X_VCCIA_F1_X_1200_SLC_DRAGON",
    "SBFT_X_VMIN_K_F2XAT_X_VCCIA_F2_X_1700_L2_DRAGON",
    "SBFT_X_VMIN_K_F2XAT_X_VCCIA_F2_X_1700_L2_LOCKSTEP",
    "SBFT_X_VMIN_K_F2XAT_X_VCCIA_F2_X_1700_BILBO",
    "SBFT_X_VMIN_K_F2XAT_X_VCCIA_F2_X_1700_TRUNKDBG",
    "SBFT_X_VMIN_K_F2XAT_X_VCCIA_F2_X_1700_SLC_DRAGON",
    "SBFT_X_VMIN_K_F3XAT_X_VCCIA_F3_X_2400_L2_DRAGON",
    "SBFT_X_VMIN_K_F3XAT_X_VCCIA_F3_X_2400_L2_LOCKSTEP",
    "SBFT_X_VMIN_K_F3XAT_X_VCCIA_F3_X_2400_BILBO",
    "SBFT_X_VMIN_K_F3XAT_X_VCCIA_F3_X_2400_TRUNKDBG",
    "SBFT_X_VMIN_K_F3XAT_X_VCCIA_F3_X_2400_SLC_DRAGON",
    "SBFT_X_VMIN_K_F4XAT_X_VCCIA_F4_X_3000_L2_DRAGON",
    "SBFT_X_VMIN_K_F4XAT_X_VCCIA_F4_X_3000_L2_LOCKSTEP",
    "SBFT_X_VMIN_K_F4XAT_X_VCCIA_F4_X_3000_BILBO",
    "SBFT_X_VMIN_K_F4XAT_X_VCCIA_F4_X_3000_TRUNKDBG",
    "SBFT_X_VMIN_K_F4XAT_X_VCCIA_F4_X_3000_SLC_DRAGON",
    "SBFT_X_VMIN_K_F1XATCCF_X_VCCIA_F1_X_1200_L2_DRAGON",
    "SBFT_X_VMIN_K_F5XATLO_X_VCCIA_F5_X_AT_F5_FREQ_L2_DRAGON",
    "SBFT_X_VMIN_K_F5XATCCFLO_X_VCCIA_F5_X_AT_F5_FREQ_L2_DRAGON",
    "SBFT_X_VMIN_K_F5XATCCF_X_VCCIA_F5_X_AT_F5_FREQ_L2_DRAGON",
    "SBFT_X_VMIN_K_VMAXXAT_X_VCCIA_F1_X_1200_L2_DRAGON",
    "SBFT_X_VMIN_K_VMAXXATCCF_X_VCCIA_F1_X_1200_L2_DRAGON",
    "SBFT_X_VMIN_K_F4XATCCF_X_VCCIA_F4_X_3000_L2_DRAGON",
    "SBFT_X_VMIN_K_VMAXXATLO_X_VCCIA_F1_X_1200_L2_DRAGON",
    "SBFT_X_VMIN_K_VMAXXATCCFLO_X_VCCIA_F1_X_1200_L2_DRAGON",
    "SBFT_X_VMIN_K_F3XATCCF_X_VCCIA_F3_X_2400_L2_DRAGON",
    "SBFT_X_VMIN_K_F4XATLO_X_VCCIA_F4_X_3000_L2_DRAGON",
    "SBFT_X_VMIN_K_F4XATCCFLO_X_VCCIA_F4_X_3000_L2_DRAGON",
    "SBFT_X_VMIN_K_F2XATCCF_X_VCCIA_F2_X_1700_L2_DRAGON",
    "SBFT_X_VMIN_K_FMINXAT_X_VCCIA_F1_X_1200_L2_DRAGON",
    "SBFT_X_VMIN_K_FMINXATCCF_X_VCCIA_F1_X_1200_L2_DRAGON"
]

# Populate a ManualInject for each test name
for test_name in test_names:
    ManualInject(test_name,
        flowResult={},
        occurrence={'default': 'true'},
        actions=[
            portData(port="1", status="Pass"),
        ]
    )