from pyqs import PortInject, ManualInject, SetModule, ctvData, portData, pinData, thermalData, userVar, cycleData, triggerData, patternData

Module = 'IPC::PTH_DTS_CXPKGS9'
SetModule(Module)

# List of test case names to inject
test_cases = [
    "DTS_X_DTSBASE_K_INIT_X_X_X_X",
    "DTS_X_PATMOD_K_INIT_X_X_X_X_DELAYTIME",
    "DTS_X_PATMOD_E_INIT_X_X_X_X_MAXREAD",
    "DTS_X_ANAFUNCAP_E_STARTANA0CPU_X_X_X_X_DTRIMCHECK_SDTCLASS",
    "DTS_X_ANAFUNCAP_E_STARTANA0CPU_X_X_X_X_VBG_ADC",
    "DTS_X_ANAFUNCAP_K_STARTANA0CPU_X_X_X_X_TAPCHECK",
    "DTS_X_ANAFUNCAP_E_STARTANA0CPU_X_X_X_X_TAPCHECK_IPVERSION",
    "DTS_X_ANAFUNCAP_E_STARTANA0CPU_X_X_X_X_CATTRIMCHECK",
    "DTS_X_AUX_E_STARTANA0CPU_X_X_X_X_BENCHTOP_FORK_CPU",
    "DTS_X_GSDS2DFF_E_STARTANA0CPU_X_X_X_X_SDTCLASSDFF2GSDS",
    "DTS_X_GSDS2DFF_E_STARTANA0CPU_X_X_X_X_SDTCLASSDFF2GSDS_CPU1",
    "DTS_X_PATMOD_E_STARTANA0CPU_X_X_X_X_SDTCLASSBGTRIM",
    "DTS_X_SCREEN_E_STARTANA0CPU_X_X_X_X_SDTCLASSBGTRIM",
    "DTS_X_TDAU_K_STARTANA0CPU_X_X_X_X_SOTSDTCLASS",
    "DTS_X_ANAFUNCAP_E_STARTANA0CPU_X_X_X_X_CATTRIM",
    "DTS_X_ANAFUNCAP_E_STARTANA0CPU_X_X_X_X_DTSTEMP",
    "DTS_X_ANAFUNCAP_E_STARTANA0CPU_X_X_X_X_DTSTEMP2",
    "DTS_X_ANAFUNCAP_E_STARTANA0CPU_X_X_X_X_DTSTEMP_GAMMA",
    "DTS_X_ANAFUNCAP_E_STARTANA0CPU_X_X_X_X_DTSTRIM",
    "DTS_X_ANAFUNCAP_E_STARTANA0CPU_X_X_X_X_DTSTRIM2",
    "DTS_X_ANAFUNCAP_E_STARTANA0CPU_X_X_X_X_DTSTRIM_GAMMA",
    "DTS_X_GSDS2DFF_E_STARTANA0CPU_X_X_X_X_SDTCLASS",
    "DTS_X_GSDS2DFF_E_STARTANA0CPU_X_X_X_X_SDTCLASS_CPU1",
    "DTS_X_SCREEN_K_STARTANA0CPU_X_X_X_X_DTSCALC",
    "DTS_X_ANAMEAS_E_STARTANA0CPU_X_X_X_X_VREFOUT1",
    "DTS_X_ANAMEAS_E_STARTANA0CPU_X_X_X_X_VBE",
    "DTS_X_ANAMEAS_E_STARTANA0CPU_X_X_X_X_VREFOUT",
    "DTS_X_PATMOD_E_STARTANA0CPU_X_X_X_X",
    "DTS_X_SCREEN_K_STARTANA0CPU_X_X_X_X_TEMPDELTA",
    "DTS_X_SCREEN_K_STARTANA0CPU_X_X_X_X_VBGDELTA",
    "DTS_X_ANAFUNCAP_E_STARTANA0CPU_X_X_X_X_DTSTEMPCHECK_SDTCLASS",
    "DTS_X_SCREEN_E_STARTANA0CPU_X_X_X_X_CATTRIPCHECK",
    "DTS_X_PATMOD_E_STARTANA0CPU_X_X_X_X_SDTCLASSCATTRIP",
    "DTS_X_ANAFUNCAP_E_STARTANA0CPU_X_X_X_X_CATTRIPCHECKPLUSMINUS",
    "DTS_X_PATMOD_E_LTTCCPU_X_X_X_X",
    "DTS_X_ANAFUNCAP_E_LTTCCPU_X_X_X_X_DTSTEMP",
    "DTS_X_SCREEN_K_LTTCCPU_X_X_X_X_TEMPDELTA"
]

# Loop through each test case and apply the same manual injection format
for test_case in test_cases:
    ManualInject(
        test_case,
        flowResult={},
        occurrence={'default': 'true'},
        actions=[
            portData(port="1", status="Pass"),
        ]
    )