name: MBOT-NVLHX28C-Scheduler

on:
  #schedule:
    # Runs at 11 PM UTC (7 AM GMT+8) || 4 AM UTC (12 PM GMT+8) || 8 AM UTC (16 PM GMT+8)
  #  - cron: '0 23 * * *'
  #  - cron: '0 4 * * *'
  #  - cron: '0 16 * * *'

  workflow_dispatch: 
    inputs:

      name:
        description: 'MV_json_file or FULL - rev1'
        # Default value if no value is explicitly provided
        default: 'FULL'
        # Input has to be provided for the workflow to run
        required: true

      targetbom:
        description: 'Option: Class_NVL_S28C | ALL | If running multi boms, using comma delimiter'
        # Default value if no value is explicitly provided
        default: 'Class_NVL_HX28C'
        # Input has to be provided for the workflow to run
        required: true

      destination:
        description: 'I:/ path to copy TP. Leave alone to not copy.'
        # Default value if no value is explicitly provided
        default: 'I:/'
        # Input has to be provided for the workflow to run
        required: true

      batfile:
        description: 'I:/ drive path to user bat file'
        # Default value if no value is explicitly provided
        default: 'None'
        # Input has to be provided for the workflow to run
        required: true

      CPUBranch:
        description: 'CPUBranchname|tag|sha|none'
        # Default value if no value is explicitly provided
        default: 'main'
        # Input has to be provided for the workflow to run
        required: true

      GCDBranch:
        description: 'GCDBranchname|tag|sha|none'
        # Default value if no value is explicitly provided
        default: 'main'
        # Input has to be provided for the workflow to run
        required: true

      HUBBranch:
        description: 'HUBBranchname|tag|sha|none'
        # Default value if no value is explicitly provided
        default: 'main'
        # Input has to be provided for the workflow to run
        required: true

      PCDBranch:
        description: 'PCDBranchname|tag|sha|none'
        # Default value if no value is explicitly provided
        default: 'main'
        # Input has to be provided for the workflow to run
        required: true

      acpy:
        description: 'Auto Content pymtpl I:\ path:'
        default: 'None'
        required: false

      email:
        description: 'Email address'
        # Default value if no value is explicitly provided
        default: 'mys.ddg.class_tpi@intel.com,nvlpcdh_classtpi@intel.com'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  MBOT-OFFLINE:
    runs-on: [self-hosted, checkers_PG]
    timeout-minutes: 120

    steps:
    - name: Log Inputs
      shell: powershell
      run: |
        if ($env:GITHUB_EVENT_NAME -eq "workflow_dispatch") {
          Write-Output "${{ toJSON(github.event.inputs) }}"
        } else {
          Write-Output "{
            \"name\": \"FULL\",
            \"targetbom\": \"Class_NVL_HX28C\",
            \"destination\": \"I:/\",
            \"batfile\": \"None\",
            \"CPUBranch\": \"main\",
            \"GCDBranch\": \"main\",
            \"HUBBranch\": \"main\",
            \"PCDBranch\": \"main\",
            \"acpy\": \"None\",
            \"email\": \"mys.ddg.class_tpi@intel.com,nvlpcdh_classtpi@intel.com\"
          }"
        }

    - name: repo_init_check
      continue-on-error: true
      run: python -u I:/tpvalidation/engtools/tptools/mtl/beta/gen1/main/tprobot.py REPO_INIT main

    - uses: actions/checkout@v6
      with: 
        fetch-depth: 0
        clean: true              # remove untracked files before checkout
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Checkout submodules
      run: |
        git submodule sync --recursive
        git submodule update --init --recursive --force

    - name: clone dielets
      run: python I:/tpvalidation/engtools/tptools/mtl/beta/gen1/main/nvl_buildtp.py ${{ github.event.inputs.targetbom || 'Class_NVL_HX28C' }} -clone
      env:
         CPU_Branch: ${{ github.event.inputs.CPUBranch }}
         GCD_Branch: ${{ github.event.inputs.GCDBranch }}
         PCD_Branch: ${{ github.event.inputs.PCDBranch }}
         HUB_Branch: ${{ github.event.inputs.HUBBranch }}

    - name: offline_run
      run: python -u I:/tpvalidation/engtools/tptools/mtl/beta/gen1/main/runner_botos.py nvl2_simmbot._ALL_.nvl_common
      env:
        DEST: ${{ github.event.inputs.destination || 'I:/' }}
        EMAIL: ${{ github.event.inputs.email || 'mys.ddg.class_tpi@intel.com,nvlpcdh_classtpi@intel.com' }}
        IN1: ${{ github.event.inputs.name || 'FULL' }}
        BATFILE: ${{ github.event.inputs.batfile || 'None' }}
        TARGETBOM: ${{ github.event.inputs.targetbom || 'Class_NVL_HX28C' }}
        CLEANTP: False
        # PUP: ${{ github.event.inputs.pup }}
