name: Coverage Calculator

on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  run_unittests:
    runs-on: [self-hosted]
    continue-on-error: true
    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        fetch-depth: 0
    - name: Fetch base branch
      run: |
        git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}

    - name: Read read_ut_sha
      id: read_ut_sha
      run: |
        SHA=$(cat unittest_sha.txt)
        if [ -z "$SHA" ]; then
          echo "ERROR: unittest_sha.txt is empty or not found!"; exit 1
        fi
        echo "sha=$SHA" >> $GITHUB_OUTPUT
    - name: Checkout pytpd-unittest
      run: |
        cd ../pytpd-unittest
        git status > /dev/null 2>&1 || { echo "ERROR: Not a valid git repository!"; exit 1; }
        git reset --hard HEAD
        git clean -fdx
        git fetch
        git checkout ${{ steps.read_ut_sha.outputs.sha }} || { echo "ERROR: SHA ${{ steps.read_ut_sha.outputs.sha }} not found in repo!"; exit 1; }

    - name: Run coverage
      run: |
        main/run_tests.py -coverage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}