"""make_collapse_tables.py — produce per-module markdown tables of collapse
candidates with OK_Ratio >= THRESH_OK and GroupSize >= THRESH_SIZE.

Reads each `<MODULE>_collapse_candidates.csv` written by recommend_collapse.py.

Usage:
    python make_collapse_tables.py <modules_root> [<glob>...]
        e.g. python make_collapse_tables.py ..\..\Modules ARR* FUN* SCN*

Output: collapse_candidates_tables.md (one ## section per module that has
qualifying rows).
"""
from __future__ import annotations
import csv
import sys
from pathlib import Path

THIS_DIR = Path(__file__).resolve().parent
THRESH_OK = 0.50
THRESH_SIZE = 2


def discover(root: Path, globs: list[str]) -> list[Path]:
    out: list[Path] = []
    if globs:
        for g in globs:
            for fam in root.glob(g):
                if fam.is_dir():
                    out.extend(d for d in fam.iterdir() if d.is_dir())
    else:
        for fam in root.iterdir():
            if fam.is_dir():
                out.extend(d for d in fam.iterdir() if d.is_dir())
    return sorted(d for d in out
                  if (d / f"{d.name}_collapse_candidates.csv").exists())


def members_short(members_str: str, token_values_str: str) -> str:
    """Display the token values (compact) instead of full member names."""
    vals = [v.strip() for v in token_values_str.split(';') if v.strip()]
    return ', '.join(vals)


def build_table(rows: list[dict]) -> str:
    out = ["| EP | Depth | Size | OK% | Items | Template | Members |",
           "|---:|---:|---:|---:|---:|---|---|"]
    for r in rows:
        ok_pct = int(round(float(r['OK_Ratio']) * 100))
        out.append(f"| {r['EntryPoint']} | {r['MaxDepth']} | "
                   f"{r['GroupSize']} | {ok_pct}% | {r['Total_Items']} | "
                   f"`{r['Template']}` | "
                   f"{members_short(r['Members'], r['TokenValues'])} |")
    return '\n'.join(out)


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print(__doc__)
        return 2
    root = Path(argv[1]).resolve()
    globs = argv[2:]
    modules = discover(root, globs)
    if not modules:
        print("[ERR] no modules with collapse_candidates.csv found")
        return 1

    sections: list[str] = []
    skipped: list[str] = []
    for m in modules:
        csv_path = m / f"{m.name}_collapse_candidates.csv"
        with csv_path.open('r', newline='', encoding='utf-8') as f:
            all_rows = list(csv.DictReader(f))
        rows = [r for r in all_rows
                if float(r['OK_Ratio']) >= THRESH_OK
                and int(r['GroupSize']) >= THRESH_SIZE
                and int(r.get('Independent', '0') or 0) == 1]
        if not rows:
            skipped.append(m.name)
            continue
        # Sort: EntryPoint desc, MaxDepth desc, GroupSize desc, OK desc, Items desc
        rows.sort(key=lambda r: (-int(r['EntryPoint']),
                                 -int(r['MaxDepth']),
                                 -int(r['GroupSize']),
                                 -float(r['OK_Ratio']),
                                 -int(r['Total_Items'])))
        sections.append(f"## {m.name}\n\n{build_table(rows)}\n")

    out = THIS_DIR / 'collapse_candidates_tables.md'
    header = (f"# Collapse Candidates by Module  "
              f"(OK >= {int(THRESH_OK*100)}%, GroupSize >= {THRESH_SIZE})\n\n"
              f"_Generated by `make_collapse_tables.py`._\n\n"
              f"Columns: **EP** = entry-point flag (1 = no other flow in module"
              f" calls any group member); **Depth** = max sub-flow chain depth"
              f" within module; **Size** = number of flows in the group; "
              f"**OK%** = fraction of FlowItems that align identically across"
              f" all members after token symbolization; **Items** = total"
              f" FlowItems compared per member; **Members** = differing"
              f" token values.\n\n---\n\n")
    body = '\n'.join(sections)
    if skipped:
        body += ("\n---\n\n## Modules with no qualifying candidates\n\n"
                 + ', '.join(f"`{n}`" for n in skipped) + "\n")
    out.write_text(header + body, encoding='utf-8')
    print(f"[out] {out}  ({len(sections)} module sections, {len(skipped)} skipped)")
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
