#!/intel/tpvalidation/engtools/tptools/mtl/pyston/pyston2.3.4/bin/pyston
"""
Guarantee value of <variable>_<Max|Min|First|Last> has to match BinMatrix.flm.usrv values. Only variables with _Max|_Min|_First|_Last will be checked.
The BinMatrix.flm.usrv is automatically generated by BinSplit team, but the BaseSpecs.usrv is manually updated.
Link: https://wiki.ith.intel.com/display/ITSpdxtp/BinMatrix+UserVars

"""
import sys
import setenv

from gadget.dictmore import xmlfunc, iter_dot_items, find_dot_items
from gadget.pylog import log
from qgates.qgate_base import QGateBase
from tp.testprogram import TestProgram
from pprint import pprint
from xml.etree import cElementTree as ElementTree
from os.path import basename
import json
import glob
import os


class BaseSpecChecker(QGateBase):

    def get_spec_vars(self, baseSpec):
        """ This function will return the value of the interested frequency and its specified value.
        Ex: {"GT_F5_FREQ_Max": "1.8"}
        """
        with open(baseSpec, 'r') as f:
            f_lines = f.readlines()

        line_count = 0
        start_of_BM_count = 0
        start_of_BM_flag = False
        end_of_BM_count = 0
        for line in f_lines:
            if ('BinMatrixManual' in line or 'FlowMatrixManual' in line) and not line.strip().startswith('#'):
                start_of_BM_count = line_count
                start_of_BM_flag = True
            elif start_of_BM_flag and '}' in line:
                end_of_BM_count = line_count
                start_of_BM_flag = False
                break
            line_count += 1

        check_dict_temp = {}
        for i in range(end_of_BM_count - start_of_BM_count):
            line = f_lines[start_of_BM_count + i]
            if 'String' in line and not line.strip().startswith('#'):
                # String GT_F5_FREQ_Max = BinMatrixRule.BomGroupRule("1.8");
                BM_var = line.strip().split('=')[0].strip().split()[-1]
                # if BM_var[-4:] == '_Max' or BM_var[-4:] == '_Min' or BM_var[-6:] == '_First' or BM_var[-5:] == '_Last':
                if BM_var.endswith(('_Max', '_Min', '_First', '_Last')):
                    if 'BinMatrixRule.BomGroupRule' in line or 'FlowMatrixRule.BomGroupRule' in line:
                        value = line.strip().split('=')[-1].strip().split('\"')[1]
                        check_dict_temp[BM_var] = value
        return check_dict_temp

    def main(self):
        """Entry point of checker"""
        check_dict = {}
        pass_checker_flag = True
        if (glob.glob(f'{self.tpobj.shareddir}/*/BaseSpecs.usrv')):
            for baseSpec in glob.glob(f'{self.tpobj.shareddir}/*/BaseSpecs.usrv'):
                check_dict = self.get_spec_vars(baseSpec)
                # Compare to the BinMatrix.flm.usrv
                if (glob.glob(f'{self.tpobj.shareddir}/Package_Shared/BinMatrix.flm.usrv')):
                    binMatrix_path = glob.glob(f'{self.tpobj.shareddir}/Package_Shared/BinMatrix.flm.usrv')[0]
                else:
                    self.add_error(226, 'BASE', f'Cannot find any BinMatrix.flm.usrv in the test program. Please verify the test program is generated correctly.')
                    return 1

                with open(binMatrix_path, 'r') as f:
                    bm_lines = f.readlines()

                for key, value in check_dict.items():
                    # Ex: GT_F5_FREQ_Max
                    freq_var, freq_indicator = key.rsplit('_', 1)   # GT_F5_FREQ, Max
                    for line in bm_lines:
                        # Array<String> GT_F5_FREQ = BinMatrixRule.BomGroupRule(["1.8", "1.8", "1.65", "1.65"]);
                        if freq_var in line and 'Array' in line:
                            if freq_var == line.strip().split('=')[0].strip().split()[-1]:
                                if 'BinMatrixRule.BomGroupRule' in line or 'FlowMatrixRule.BomGroupRule' in line:
                                    freq_array = line.strip().split('[')[1].split(']')[0].replace('\"', "").split(',')
                                    error_flag = False
                                    if freq_indicator == 'First':
                                        error_flag = (value != freq_array[0])

                                    elif freq_indicator == 'Last':
                                        error_flag = (value != freq_array[-1])

                                    elif freq_indicator == 'Max':
                                        float_freq_array = [float(x) for x in freq_array]
                                        max_freq = max(float_freq_array)
                                        error_flag = (float(value) != max_freq)

                                    elif freq_indicator == 'Min':
                                        float_freq_array = [float(x) for x in freq_array]
                                        min_freq = min(float_freq_array)
                                        error_flag = (float(value) != min_freq)

                                    if error_flag:
                                        pass_checker_flag = False
                                        print(f'In {baseSpec}, {key} has value of {value} which does NOT meet the {freq_indicator} value of {freq_var} in {binMatrix_path}')
                                        self.add_error(226, 'BASE', f'In {baseSpec}, {key} has value of {value} which does NOT meet the {freq_indicator} value of {freq_var} in {binMatrix_path}.')
                                    else:
                                        print('The Base Specs checker is passed.')
                                        self.add_pass(226, 'BASE')      # for every fail, there should be a pass counter to tell the check worked

        else:
            print('Could NOT find any BaseSpecs.usrv. Skip the check')


if __name__ == '__main__':  # pragma: no cover
    assert len(sys.argv) == 2, 'Usage Error!\n\nPls specify .env file as first args'
    BaseSpecChecker(TestProgram(sys.argv[1])).run()
