#!/intel/tpvalidation/engtools/tptools/mtl/pyston/pyston2.3.4/bin/pyston
"""
Ensures all required PCS tokens are available and generated by the TP

#1 - PrimeLogPcsTokensTestMethod" which print: PCS_SKTCN and PCS_SKTRP
#2 - PrimeThermalSingleMeasurementTestMethod which print: PCS_SOT, PCS_TJRISE, PCS_TJDROOP, PCS_DTSMAX
#3 - Tokens that are printed from the SC_RECIPE cannot be checked.
     Tokens that are generated by the SC_RECIPE are: PCS_SETPOINT, PCS_STIM, PCS_VMU
"""
import setenv      # must be first in the imports
from gadget.pylog import log
from qgates.qgate_base import QGateBase
from tp.testprogram import TestProgram
from pprint import pprint
import sys
from itertools import chain


class ReqPCSTokens(QGateBase):

    def main(self):
        # No need to run this check for ENG_TP
        if self.tpobj.get_buildtype() == 'ENG_TP':
            log.info('-i- ReqPCSTokens qgate is skipped due to ENG_TP')
            return 1

        ptsmt = []
        plpt = []
        main = self.tpobj.mtpl.iter_flows('MAIN', bypass=True, edict=True)
        testplanend = self.tpobj.mtpl.iter_flows('TESTPLANENDFLOW', bypass=True, edict=True)
        for mod, item, params in chain(main, testplanend):
            if 'PrimeThermalSingleMeasurementTestMethod' == params['TEMPLATE'] and 'PTH_' in mod:
                ptsmt.append(mod)
                self.add_pass(214, "BASE")

            if 'PrimeLogPcsTokensTestMethod' == params['TEMPLATE'] and 'PTH_' in mod:
                # print(mod, item, params['TEMPLATE'])
                plpt.append(mod)
                self.add_pass(215, "BASE")

        if len(ptsmt) == 0:
            msg = ("PTH module missing PrimeThermalSingleMeasurementTestMethod template to generate "
                   "PCS_SOT, PCS_TJRISE, PSC_TJDROOP and PCS_DTSMAX required tokens")
            self.add_error(214, "BASE", msg)   # This is how to specify error

        if len(plpt) == 0:
            msg = ('PTH module missing PrimeLogPcsTokensTestMethod template to generate PCS_SKTCN '
                   'and PCS_SKTRP required tokens')
            self.add_error(215, "BASE", msg)

        return 2     # for unitest, success


if __name__ == '__main__':  # pragma: no cover
    assert len(sys.argv) == 2, 'Usage Error!\n\nPls specify .env file as first args'
    ReqPCSTokens(TestProgram(sys.argv[1]).pickle_init()).run()
