from pyqs import PortInject, ManualInject, SetModule, ctvData, portData, pinData, thermalData, userVar, triggerData, patternData

SetModule('IPC::ARR_COMMON_CKX')

test_names = [
   	 "ALL_X_UF_K_INIT_X_X_X_X_PINMAP",
	 "ALL_X_FUSECONFIG_K_STARTCPUPATMODSPKG_X_X_X_X_MBIST_RWA_PATCONFIG",
	 "ALL_X_HRY_E_STARTCPUPATMODSPKG_X_X_X_X_MBIST_HRY_INIT",
	 "ALL_CORE_X_E_STARTCPUPATMODSPKG_X_X_X_X_MBIST_DFF_READ",
	 "ALL_X_SCREEN_K_STARTCPUPATMODSPKG_X_X_X_X_ATOM_REP2FUSE",
	 "ALL_X_SCREEN_K_STARTCPUPATMODSPKG_X_X_X_X_VFDM_REBUILD",
	 "X_CPU_GETDFF_E_STARTCPUPATMODSPKG_X_X_X_X_SVHCS",
	 "X_CPU_GETDFF_E_STARTCPUPATMODSPKG_X_X_X_X_SVFDS1",
	 "X_CPU_GETDFF_E_STARTCPUPATMODSPKG_X_X_X_X_SVFDS2",
	 "ALL_X_SCREEN_E_STARTCPUPATMODSPKG_X_X_X_X_SET_FDS",
	 "ALL_X_FUSECONFIG_K_STARTCPUPATMODSPKG_X_X_X_X_REPAIR",
	 "ALL_ATOM__K_STARTCPUPATMODSPKG_X_X_X_X_CONVERT_HEX2BIN_VFDM_DFF",
	 "ALL_X_SCREEN_K_STARTCPUPATMODSPKG_X_X_X_X_ATOM_VFDM_REBUILD_1",
	 "ALL_X_AUX_K_ENDCPUPKG_X_X_X_X_WRITE_CSVFDS",
	 "ALL_X_AUX_K_ENDCPUPKG_X_X_X_X_WRITE_CSVHCS",
	 "X_CPU_GETDFF_K_STARTCPUPATMODSPKG_X_X_X_X_CSVHCS",
	 "X_CPU_GETDFF_K_STARTCPUPATMODSPKG_X_X_X_X_CSVFDS",
	 "ALL_X_SCREEN_E_STARTCPUPATMODSPKG_X_X_X_X_MBIST_DFF_RESET_REVERSE",
	 "ALL_X_SCREEN_E_STARTCPUPATMODSPKG_X_X_X_X_MBIST_SORT_TP",
	 "ALL_X_SCREEN_E_STARTCPUPATMODSPKG_X_X_X_X_MBIST_DFF_RESET_DEFAULT",
	 "ALL_X_SCREEN_E_STARTCPUPATMODSPKG_X_X_X_X_SET_FDS_CSM",
]

# Populate a ManualInject for each test name
for test_name in test_names:
    ManualInject(test_name,
        flowResult={},
        occurrence={'default': 'true'},
        actions=[
            portData(port="1", status="Pass"),
        ]
    )

