#!/intel/tpvalidation/engtools/tptools/mtl/pyston/pyston2.3.4/bin/pyston -u
"""
msbuild wrapper for NVL

Usage:
msbuild.py NVL_CPU.sln <BOM>      # Fixer will do specific BOM. Then, updates Torch folder on Given BOM.
msbuild.py NVL_CPU.sln All        # Only run msbuild for all BOMs which is non-bom-specific, no fixer or postproc.
"""
import sys
try:
    import setenv      # must be first in imports
except ImportError:    # pragma: no cover    - Used when local qgate .py is in tp area
    sys.path.append('Shared/BaseInputs/pytpd')     # This works, as long as script is called from TP root area
    sys.path.append('I:/tpvalidation/engtools/tptools/mtl/beta/latest')

from gadget.errors import confirm
from gadget.pylog import log
from gadget.files import File, glob_one_only, check_and_del
from gadget.disk import Chdir, mkdirs
from gadget.gizmo import Elapsed
from main.torch_mv import DoMV
from gadget.shell import SystemCall, putquotes, IS_UNIX, IS_WIN
from gadget.errors import exit1
from os.path import exists, dirname, basename, isdir
from gadget.printmore import RED, NORED
from tp.testprogram import TestProgram, Env
from mod.envreorder import EnvReorder
from mod.tpswitch import TPSwitch
import glob
import shutil
import os
import re


# Below is a simple way to inform user if they are python version <3.5. This is checked before any other code during the Parsing phase.
f'If you see SyntaxError, this means your python version is old. Pls upgrade to python3.8 minimum: http://python.org/downloads'


class MSBuild:

    choices = (r'C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\MSBuild.exe',
               r'C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\amd64\MSBuild.exe')

    def __init__(self):
        self._ut_tpproj = []

    def get_envfile_common(self, inputbom, root):
        """Return the (only) envfile from current working dir"""
        confirm(inputbom, 'No BOM specified', 'Please make sure the BOM is specified in the msbuild.py commandline')

        wild = f'{root}/Shared/BaseInputs/Common/Common_{inputbom}/*_Common.env'
        res = glob.glob(wild)
        res = [x for x in res if not x.endswith('.g.env')]    # These are Torch autogenerated files on pobj cache

        confirm(len(res) == 1, f'Expecting 1 common .env file. Found: {res}', 'Pls check')
        return res[0]    # There is only one

    def main(self, slnfile_input=None, bom_input=None, ispostproc=True):
        """
        Main entry point
        :param slnfile_input: sln file
        :param bom_input: which bom
        :param ispostproc: Set to False to not postproc
        :return:
        """
        slnfile = slnfile_input if slnfile_input else sys.argv[1]
        # The dll copy path is the same among all boms, so grab S28C as default.
        user_input_bom = self.get_user_input(bom_input)
        if user_input_bom == 'All':
            # hardcode S28C for All case
            inputbom = 'Class_NVL_S28C'
        else:
            inputbom = self.get_user_input(bom_input)
        root = dirname(slnfile)

        if not root:
            root = '.'
        sw = Elapsed()

        print(f'CWD: {os.getcwd()}')
        print(f'inputbom: {inputbom}')
        print(f'root: {root}')

        envcom = self.get_envfile_common(inputbom, root)
        print(f'Using envfile: {envcom}')

        if 'PRIME_DLL_PATH' in File(envcom).read():
            self.copy_dll(envcom, root)
        else:
            self.build_dll(slnfile, root)

        print(f"MSBUILD is DONE in {sw}.")

        if not user_input_bom == 'All':
            TPSwitch.main(inputbom, root, 'pre-build')

            self.auto_content_pymtpl(inputbom, root)

            # Torch fixer
            self.torch_fixer(inputbom, slnfile, root)

            self.ip_trialvars_hack(inputbom, root)

            self.env_reorder(root, ispostproc, inputbom)

    def torch_fixer(self, inputbom, slnfile, root):
        """
        Call torch fixer
        """
        swall = Elapsed()
        porbom = inputbom if inputbom else '*'    # all boms
        with Chdir(dirname(slnfile)):
            torchexe = DoMV.get_torch_exe()
        list_tpproj = glob.glob(f'{root}/POR_TP/{porbom}/*.tpproj')
        portps = os.listdir(f'{root}/POR_TP')
        confirm(len(list_tpproj), f'Found no tpproj for bom={porbom}', f'Check POR_TP folder contains: {portps}')
        log.info(f'-i- TorchFixer: will process {len(list_tpproj)} tpprojs')
        for tpproj in list_tpproj:
            sw = Elapsed()
            cmd = f'{torchexe} fix-tp --sln-config {porbom} -s {slnfile} -p {tpproj}'
            code, out = SystemCall(cmd, disp=True).run_outtxt()
            log.info(out)
            log.info(f'fix-tp is complete in {sw} for {tpproj}')
            confirm(not code, f'Command failed: {cmd}', 'Check output above.')
            self._ut_tpproj.append(tpproj)     # unittest

        print(f"Torch fixer is DONE in {swall}.")

    def ip_trialvars_hack(self, bom, root):
        """
        See https://wiki.ith.intel.com/display/ITSpdxtp/NVL+fulltp+journal#NVLfulltpjournal-Jul17TrialVarsPR
        Since Torch does not support the IP names in dielet. Torch ticket: tbd
        :return:
        """
        expect_file = f'{root}/Shared/Modules/TPI/TPI_TRIALVAR_CXX/cpu_ip_trials.mtpl'
        if not exists(expect_file):
            log.info(f'-i- ip_trialvars_hack() is skipped, {expect_file} not exist')
            return 1

        dmap = {'IPC': '../../Shared/Modules/TPI/TPI_TRIALVAR_CXX/cpu_ip_trials.mtpl',
                'IPG': '../../Shared/Modules/TPI/TPI_TRIALVAR_GXX/gcd_ip_trials.mtpl',
                'IPP': '../../Shared/Modules/TPI/TPI_TRIALVAR_PXX/pcd_ip_trials.mtpl',
                'IPH': '../../Shared/Modules/TPI/TPI_TRIALVAR_HXX/hub_ip_trials.mtpl'
                }

        stpl = f'{root}/POR_TP/{bom}/SubTestPlan.stpl'
        lines = File(stpl).raw()

        # Add the new line on existing IP block
        ip = None
        robj = re.compile(r'IPName\s+(\S+)\b')
        final = []
        foundip = set()
        for line in lines:
            res = robj.search(line)
            if res:
                ip = res.group(1)
                foundip.add(ip)
            if line.strip().startswith('Common') and ip:
                final.append(line)
                final.append(f'        "{dmap[ip]}";\n')
                continue
            if line.strip().startswith('}'):
                ip = None
            final.append(line)

        # Add the new blocks
        final2 = []
        ip = None
        for line in final:
            res = robj.search(line)
            if res:
                ip = res.group(1)
            if line.strip().startswith('}') and ip:
                final2.append(line)
                for newip in sorted(dmap):
                    if newip in foundip:
                        continue
                    final2.append(f'    IPName {newip}\n')
                    final2.append('    {\n')
                    final2.append(f'        "{dmap[newip]}";\n')
                    final2.append('    }\n')
                ip = None
                continue
            final2.append(line)

        File(stpl).rewrite(''.join(final2), 'ip_trialvars_hack()')

    @classmethod
    def auto_content_pymtpl(cls, bom, root):
        """Call auto content pymtpl if specified"""
        pypath = os.environ.get('ACPY')
        if (not pypath) or pypath == 'None':
            return 1     # do nothing if this var is not set

        if not pypath.startswith('ACPY:'):
            return 2

        pypath = pypath[5:]

        with Chdir(root):
            log.info(f'-i- Auto Content Start: {pypath}, cwd: {os.getcwd()}')
            from pymtpl.core import PyMtpl
            PyMtpl.run(pypath, f'POR_TP/{bom}/EnvironmentFile.env')

    def env_reorder(self, root, ispostproc, inputbom):
        """
        Call env reorder for all the BOMs
        :return:
        """
        if not ispostproc:
            return -1

        wildcard = inputbom if inputbom else '*'

        cnt = 0
        for env in glob.glob(f'{root}/POR_TP/{wildcard}/Env*.env'):
            cnt += 1
            log.info(f'-i- Starting env reorder for {basename(dirname(env))}')
            EnvReorder(TestProgram(env)).main(disp=False, update=True)

        return cnt     # for unittest

    @classmethod
    def copy_folder_fast(cls, src, dest, quickbuild_mode=bool(os.environ.get('QUICKBUILD', 'false').lower() == 'true')):
        """
        Copy folder from src to dest. Uses robocopy on Windows when QUICKBUILD=true
        for multi-threaded fast copy, otherwise falls back to shutil.copytree.
        If robocopy fails, automatically falls back to shutil.copytree.

        # robocopy options:
        # /E     - Copy subdirectories including empty ones
        # /MT:4 - Multi-threaded copy with 4 threads
        # /R:1   - Number of retries (default is 1 million)
        # /W:1   - Wait time between retries in seconds
        # /NFL   - No file listing (quieter output)
        # /NDL   - No directory listing
        # /NJH   - No job header
        # /NJS   - No job summary
        cmd = f'robocopy "{srcdir}" "{outdir}" /E /MT:4 /R:1 /W:1 /NFL /NDL /NJH /NJS'
        log.info(f'-i- copytp_quickbuild: running robocopy with 4 threads')

        ecode, sout, serr = SystemCall(cmd, disp=True).run_sout_serr()

        # robocopy exit codes: 0-7 are success, 8+ are errors
        # 0 = No files copied, no failure
        # 1 = Files copied successfully
        # 2 = Extra files/dirs detected
        # 4 = Mismatched files/dirs detected
        # 8+ = Errors occurred

        :param src: Source folder path
        :param dest: Destination folder path
        :param quickbuild: Set to True for quickbuild
        :return: None
        """

        if quickbuild_mode and IS_WIN:
            # Use robocopy for multi-threaded fast copy
            cmd = f'robocopy "{src}" "{dest}" /E /MT:4 /R:1 /W:1 /NFL /NDL /NJH /NJS'
            log.info(f'-i- copy_folder_fast: running robocopy with 4 threads')
            sw = Elapsed()
            ecode, sout, serr = SystemCall(cmd, disp=True).run_sout_serr()

            # robocopy exit codes: 0-7 are success, 8+ are errors
            if ecode >= 8:
                log.info(f'-w- copy_folder_fast: robocopy returned error code {ecode}')
                if serr:
                    log.info(f'-w- robocopy stderr: {serr}')
                log.info(f'-i- copy_folder_fast: falling back to shutil.copytree')
                check_and_del(dest, mv_on_error=True)    # Clean up partial folder from failed robocopy
                shutil.copytree(src, dest)
            else:
                log.info(f'-i- copy_folder_fast: robocopy completed with code {ecode}')
            log.info(f'-i- Copy elapsed: {sw}')
        else:
            # Standard shutil copy
            shutil.copytree(src, dest)

    def copy_dll(self, envcom, root):
        """
        Copy dll routine. Uses optimized robocopy when QUICKBUILD=true on Windows.

        :param envcom: Which env file
        :param root: Root of TP
        :return: None
        """
        print(f'-i- Starting copy_dll(): env to read: {envcom}')
        envobj = Env(os.path.abspath(envcom))
        allitems = envobj.get_contents('PRIME_DLL_PATH', islist=True)
        allitems = [x.strip() for x in allitems]       # remove any whitespace

        # ================== Copy Freddy dll first
        # folder structure: I:/tpapps/userlibs/nvl/prime_v13.2.0-ddg251600/lib/Release/net6.0
        # PRIME_DLL_PATH = "I:/tpapps/userlibs/nvl/prime_v13.2.0-ddg251600"
        # output: Usercode/lib/Release/net6.0
        itemf = f'{allitems[0]}/lib/Release'
        destf = f'{root}/Usercode/lib/Release'         # Usercode/lib/Release/net6.0
        check_and_del(destf, mv_on_error=True)
        mkdirs(dirname(destf))
        print(f"Copying Main dll: {itemf} to {destf}")
        self.copy_folder_fast(itemf, destf)

        # ================== Copy custom dll's
        # folder structure: I:/tpapps/userlibs/nvl/modules/prime_v13.2.0/binning/UPS2517_UC1.0_eng/*.dll
        # BINNING_USERCODE_PATH = "binning/UPS2517_UC1.0_eng"
        # PRIME_DLL_PATH = "<freddypath>; I:/tpapps/userlibs/nvl/modules/prime_v13.2.0/$BINNING_USERCODE_PATH
        # output: Usercode/lib/Release/custom/binning/UPS2517_UC1.0_eng/*.dll
        for item in allitems[1:]:                              # /path/binning/UPS2517_UC1.0_eng
            folder2 = basename(item)                           # UPS2517_UC1.0_eng
            folder1 = basename(dirname(item))                  # binning
            dest = f'{root}/Usercode/lib/Release/custom/{folder1}/{folder2}'
            check_and_del(dest, mv_on_error=True)
            mkdirs(dirname(dest))
            print(f"Copying Custom dll: {item} to {dest}")
            self.copy_folder_fast(item, dest)

    def build_dll(self, slnfile, root):
        """
        Traditional build dll
        :param slnfile:
        :param root:
        :return:
        """
        # TODO: Refactor below so it's unindent once
        # TODO: Refactor move copy_dll_file() and get_envfile_common() to bottom

        print('-i- Starting build_dll()')
        if 'SKIPBUILD' in os.environ:
            print("-i- Skipping build due to SKIPBUILD")
        else:
            for msbuild_exe in self.choices:
                if exists(msbuild_exe):
                    break
            else:
                exit1(f'[{self.choices[0]}] does not exist', 'Where is MSBuild.exe?')

            # run it
            cmd = ([msbuild_exe, slnfile] +
                   "-m -verbosity:normal -nologo -restore -p:Configuration=Release".split() +
                   ["-p:Platform=Any CPU"])
            log.info("CMD: %s" % ' '.join(putquotes(cmd)))
            code, sout, serr = SystemCall(cmd, disp=False).run_sout_serr()

            # print only error or warning lines
            for line in (sout + serr).split('\n'):
                if 'error' in line.lower() or 'warning' in line.lower():
                    log.info(line[:512])

            # expect "1 Error(s)" in sout
            success = '1 Error(s)'
            big_fail = f'''Check for errors in the msbuild log above.
{RED}
#######     #     ###  #
#          # #     #   #
#         #   #    #   #
#####    #     #   #   #
#        #######   #   #
#        #     #   #   #
#        #     #  ###  #######
{NORED}
'''
            for line in sout.split('\n'):
                line = line.strip()
                if line == success:
                    break
            else:
                exit1(f"Build Errors found. Expecting '{success}' in the build.",
                      big_fail)

            # Make sure lib/ and bin/ exist
            confirm(isdir(f'{root}/UserCode/lib'),
                    f'{root}/UserCode/lib is missing. This means msbuild failed.',
                    big_fail)

    def get_user_input(self, bom_input):
        """Return the user input, if exist. None if not"""
        if bom_input:
            return bom_input
        if len(sys.argv) >= 3:
            return sys.argv[2]
        return 'All'    # all boms


if __name__ == '__main__':  # pragma: no cover
    MSBuild().main()
