"""
methods class - Definition of a testclass
# Create a script later that will populate this file based on all of the prime headers
This file is semi-autogenerated (Reason: it is still modified, when we want default values)
"""
from pymtpl.core import BaseMethod


class PrimeThermalSingleMeasurementTestMethod(BaseMethod):

    def __init__(self,
                 name,
                 IntegrityHighLimit=None,
                 IntegrityLowLimit=None,
                 LowerTolerance=None,
                 PinNames=None,
                 UpperTolerance=None,
                 _fitem=None,
                 _comment=None):
        self._init(name, locals())


class VminTC(BaseMethod):

    def __init__(self,
                 name,
                 Basenumbers = None,
                 EndVoltageLimits=None,
                 FailCaptureCount=999,     # This is the default value if not specified
                 FeatureSwitchSettings=None,
                 FivrCondition=None,
                 ForwardingMode=None,
                 Patlist=None,
                 TimingsTc=None,
                 LevelsTc=None,
                 BypassPort=None,
                 LogLevel=None,
                 _fitem=None,
                 _comment=None):
        self._init(name, locals())

class ApexTC(BaseMethod):

    def __init__(self,
                 name,
                 Basenumbers = None,
                 EndVoltageLimits=None,
                 FailCaptureCount=999,     # This is the default value if not specified
                 FeatureSwitchSettings=None,
                 FivrCondition=None,
                 ForwardingMode=None,
                 Patlist=None,
                 TimingsTc=None,
                 LevelsTc=None,
                 BypassPort=None,
                 LogLevel=None,
                 _fitem=None,
                 _comment=None):
        self._init(name, locals())