from pyqs import PortInject, ManualInject, SetModule, ctvData, portData, pinData, thermalData, userVar, triggerData, patternData

SetModule('IPC::SCN_ATOM_CX816')

test_names = [
 	"ATSPEED_ATOM_VMIN_K_F1XAT_X_AT_F1_1200_M0",
	"ATSPEED_ATOM_VMIN_K_F1XAT_X_AT_F1_1200_M1",
	"ATSPEED_ATOM_VMIN_K_F1XAT_X_AT_F1_1200_M2",
	"ATSPEED_ATOM_VMIN_K_F1XAT_X_AT_F1_1200_M3",
	"ATSPEED_ATOM_VMIN_K_F5XAT_X_AT_F5_X_FREQ_M0_APEX",
	"ATSPEED_ATOM_VMIN_K_F5XAT_X_AT_F7_3600_M0",
	"ATSPEED_ATOM_VMIN_K_F5XAT_X_AT_F6_3400_M0",
	"ATSPEED_ATOM_VMIN_K_F5XAT_X_AT_F5_3200_M0",
	"ATSPEED_ATOM_VMIN_K_F5XAT_X_AT_F5_X_FREQ_M1_APEX",
	"ATSPEED_ATOM_VMIN_K_F5XAT_X_AT_F7_3600_M1",
	"ATSPEED_ATOM_VMIN_K_F5XAT_X_AT_F6_3400_M1",
	"ATSPEED_ATOM_VMIN_K_F5XAT_X_AT_F5_3200_M1",
	"ATSPEED_ATOM_VMIN_K_F5XAT_X_AT_F5_X_FREQ_M2_APEX",
	"ATSPEED_ATOM_VMIN_K_F5XAT_X_AT_F7_3600_M2",
	"ATSPEED_ATOM_VMIN_K_F5XAT_X_AT_F6_3400_M2",
	"ATSPEED_ATOM_VMIN_K_F5XAT_X_AT_F5_3200_M2",
	"ATSPEED_ATOM_VMIN_K_F5XAT_X_AT_F5_X_FREQ_M3_APEX",
	"ATSPEED_ATOM_VMIN_K_F5XAT_X_AT_F7_3600_M3",
	"ATSPEED_ATOM_VMIN_K_F5XAT_X_AT_F6_3400_M3",
	"ATSPEED_ATOM_VMIN_K_F5XAT_X_AT_F5_3200_M3",
	"ATSPEED_ATOM_SB_K_VMAXXAT_X_AT_MAX_F7_3600_M0",
	"ATSPEED_ATOM_SB_K_VMAXXAT_X_AT_MAX_F7_3600_M1",
	"ATSPEED_ATOM_SB_K_VMAXXAT_X_AT_MAX_F7_3600_M2",
	"ATSPEED_ATOM_SB_K_VMAXXAT_X_AT_MAX_F7_3600_M3",
	"STUCKAT_ATOM_SB_K_VMAXXAT_X_AT_MAX_X_F1_M0",
	"STUCKAT_ATOM_SB_K_VMAXXAT_X_AT_MAX_X_F1_M1",
	"STUCKAT_ATOM_SB_K_VMAXXAT_X_AT_MAX_X_F1_M2",
	"STUCKAT_ATOM_SB_K_VMAXXAT_X_AT_MAX_X_F1_M3",
	"ATSPEED_ATOM_VMIN_K_F4XAT_X_AT_F4_3000_M0",
	"ATSPEED_ATOM_VMIN_K_F4XAT_X_AT_F4_3000_M1",
	"ATSPEED_ATOM_VMIN_K_F4XAT_X_AT_F4_3000_M2",
	"ATSPEED_ATOM_VMIN_K_F4XAT_X_AT_F4_3000_M3",
	"ATSPEED_ATOM_VMIN_K_F3XAT_X_AT_F3_2400_M0",
	"ATSPEED_ATOM_VMIN_K_F3XAT_X_AT_F3_2400_M1",
	"ATSPEED_ATOM_VMIN_K_F3XAT_X_AT_F3_2400_M2",
	"ATSPEED_ATOM_VMIN_K_F3XAT_X_AT_F3_2400_M3",
	"ATSPEED_ATOM_VMIN_K_F2XAT_X_AT_F2_1700_M0",
	"ATSPEED_ATOM_VMIN_K_F2XAT_X_AT_F2_1700_M1",
	"ATSPEED_ATOM_VMIN_K_F2XAT_X_AT_F2_1700_M2",
	"ATSPEED_ATOM_VMIN_K_F2XAT_X_AT_F2_1700_M3",
	"ATSPEED_ATOM_VMIN_K_FMINXAT_X_AT_FMIN_0400_M0",
	"ATSPEED_ATOM_VMIN_K_FMINXAT_X_AT_FMIN_0400_M1",
	"ATSPEED_ATOM_VMIN_K_FMINXAT_X_AT_FMIN_0400_M2",
	"ATSPEED_ATOM_VMIN_K_FMINXAT_X_AT_FMIN_0400_M3",
	"ATSPEED_ATOM_SB_K_FMINXAT_X_AT_NOM_X_M0_FF_SEARCH",
	"ATSPEED_ATOM_SB_K_FMINXAT_X_AT_NOM_X_M1_FF_SEARCH",
	"ATSPEED_ATOM_SB_K_FMINXAT_X_AT_NOM_X_M2_FF_SEARCH",
	"ATSPEED_ATOM_SB_K_FMINXAT_X_AT_NOM_X_M3_FF_SEARCH",
]

# Populate a ManualInject for each test name
for test_name in test_names:
    ManualInject(test_name,
        flowResult={},
        occurrence={'default': 'true'},
        actions=[
            portData(port="1", status="Pass"),
        ]
    )
	
