from pyqs import PortInject, ManualInject, SetModule, ctvData, portData, pinData, thermalData, userVar, cycleData, triggerData, patternData

Module = 'IPC::PTH_DTS_CX816'
SetModule(Module)

# List of test case names to inject
test_cases = [
    "DTS_X_PATMOD_K_INIT_X_X_X_X_DELAYTIME",
    "DTS_X_PATMOD_E_INIT_X_X_X_X_MAXREAD",
    "DTS_X_ANAFUNCAP_K_STARTANA0CPU_X_X_X_X_TAPCHECK",
    "DTS_X_ANAFUNCAP_E_STARTANA0CPU_X_X_X_X_TAPCHECK_IPVERSION",
    "DTS_X_AUX_E_STARTANA0CPU_X_X_X_X_BENCHTOP_FORK",
    "DTS_X_AUX_E_STARTANA0CPU_X_X_X_X_TPREV_FORK",
    "DTS_X_PATMOD_E_STARTANA0CPU_X_X_X_X_DLVR_RESET_VOLTAGE",
    "DTS_X_GSDS2DFF_E_STARTANA0CPU_X_X_X_X_SDTCLASSDFF2GSDS",
    "DTS_X_PATMOD_E_STARTANA0CPU_X_X_X_X_SDTCLASSBGTRIM",
    "DTS_X_SCREEN_E_STARTANA0CPU_X_X_X_X_SDTCLASSBGTRIM",
    "DTS_X_TDAU_K_STARTANA0CPU_X_X_X_X_SOTSDTCLASS",
    "DTS_X_ANAFUNCAP_E_STARTANA0CPU_X_X_X_X_CATTRIM",
    "DTS_X_ANAFUNCAP_E_STARTANA0CPU_X_X_X_X_CATTRIM2",
    "DTS_X_ANAFUNCAP_E_STARTANA0CPU_X_X_X_X_DTSTEMP",
    "DTS_X_ANAFUNCAP_E_STARTANA0CPU_X_X_X_X_DTSTEMP2",
    "DTS_X_ANAFUNCAP_E_STARTANA0CPU_X_X_X_X_DTSTRIM",
    "DTS_X_ANAFUNCAP_E_STARTANA0CPU_X_X_X_X_DTSTRIM2",
    "DTS_X_GSDS2DFF_E_STARTANA0CPU_X_X_X_X_SDTCLASS",
    "DTS_X_SCREEN_K_STARTANA0CPU_X_X_X_X_DTSCALC",
    "DTS_X_ANAMEAS_E_STARTANA0CPU_X_X_X_X_VBE",
    "DTS_X_ANAMEAS_E_STARTANA0CPU_X_X_X_X_VREFOUT",
    "DTS_X_PATMOD_E_STARTANA0CPU_X_X_X_X",
    "DTS_X_SCREEN_K_STARTANA0CPU_X_X_X_X_TEMPDELTA",
    "DTS_X_SCREEN_K_STARTANA0CPU_X_X_X_X_VBGDELTA",
    "DTS_X_SCREEN_E_STARTANA0CPU_X_X_X_X_CATTRIPCHECK",
    "DTS_X_PATMOD_E_STARTANA0CPU_X_X_X_X_SDTCLASSCATTRIP",
    "DTS_X_ANAFUNCAP_E_STARTANA0CPU_X_X_X_X_CATTRIPCHECKPLUSMINUS",
    "DTS_X_AUX_E_LTTCCPU_X_X_X_X_TPREV_FORK",
    "DTS_X_PATMOD_E_LTTCCPU_X_X_X_X_DLVR_RESET_VOLTAGE",
    "DTS_X_TDAU_E_LTTCCPU_X_X_X_X_SOTLTTC",
    "DTS_X_ANAFUNCAP_E_LTTCCPU_X_X_X_X_DTSTRIM",
    "DTS_X_ANAFUNCAP_E_LTTCCPU_X_X_X_X_DTSTRIM2",
    "DTS_X_ANAFUNCAP_E_LTTCCPU_X_X_X_X_CATTRIM",
    "DTS_X_ANAFUNCAP_E_LTTCCPU_X_X_X_X_CATTRIM2",
    "DTS_X_SCREEN_K_LTTCCPU_X_X_X_X_DTSCALC",
    "DTS_X_GSDS2DFF_E_LTTCCPU_X_X_X_X_SDTCLASS",
    "DTS_X_PATMOD_E_LTTCCPU_X_X_X_X",
    "DTS_X_ANAFUNCAP_E_LTTCCPU_X_X_X_X_DTSTEMP",
    "DTS_X_ANAFUNCAP_E_LTTCCPU_X_X_X_X_DTSTEMP2",
    "DTS_X_SCREEN_K_LTTCCPU_X_X_X_X_TEMPDELTA",
    "DTS_X_ANAMEAS_E_LTTCCPU_X_X_X_X_VREFOUT",
    "DTS_X_ANAMEAS_E_LTTCCPU_X_X_X_X_VBE",
    "DTS_X_SCREEN_K_LTTCCPU_X_X_X_X_VBGDELTA"
]

# Loop through each test case and apply the same manual injection format
for test_case in test_cases:
    ManualInject(
        test_case,
        flowResult={},
        occurrence={'default': 'true'},
        actions=[
            portData(port="1", status="Pass"),
        ]
    )