name: MBOT_OFFLINE

on:
  workflow_dispatch: 
    inputs:

      name:
        description: 'MV_json_file or FULL - rev1'
        # Default value if no value is explicitly provided
        default: 'FULL'
        # Input has to be provided for the workflow to run
        required: true

      targetbom:
        description: 'Option: Class_NVL_S28C | ALL | If running multi boms, using comma delimiter'
        # Default value if no value is explicitly provided
        default: 'Class_NVL_S28C'
        # Input has to be provided for the workflow to run
        required: true
      
      destination:
        description: 'I:/ path to copy TP. Leave alone to not copy.'
        # Default value if no value is explicitly provided
        default: 'I:/'
        # Input has to be provided for the workflow to run
        required: true

      COMMONBranch:
        description: 'CommonBranchname|tag|sha|main'
        # Default value if no value is explicitly provided
        default: 'main'
        # Input has to be provided for the workflow to run
        required: true

      batfile:
        description: 'I:/ drive path to user bat file'
        # Default value if no value is explicitly provided
        default: 'None'
        # Input has to be provided for the workflow to run
        required: true

      repjson:
        description: 'replace_for_mv_json_file_name'
        # Default value if no value is explicitly provided
        default: 'None'
        # Input has to be provided for the workflow to run
        required: true

      email:
        description: 'Email address'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: true


jobs:
  MBOT_OFFLINE:
    runs-on: [self-hosted, checkers]
    timeout-minutes: 120

    steps:
    - name: Log Inputs
      run: echo "${{ toJSON(github.event.inputs) }}"

    - name: repo_init_check
      continue-on-error: true
      run: python -u I:/tpvalidation/engtools/tptools/mtl/beta/gen1/main/tprobot.py REPO_INIT main

    - uses: actions/checkout@v6
      with: 
        fetch-depth: 0
        clean: true              # remove untracked files before checkout
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Checkout submodules
      run: |
        git submodule sync --recursive
        git submodule update --init --recursive --force

    - name: Offline run
      run: python -u I:/tpvalidation/engtools/tptools/mtl/beta/gen1/main/runner_botos.py nvl2_simmbot._ALL_.nvl_dielet
      env:
          DEST: ${{ github.event.inputs.destination }}
          EMAIL: ${{ github.event.inputs.email }}
          IN1: ${{ github.event.inputs.name }}
          BATFILE: ${{ github.event.inputs.batfile }}
          TARGETBOM: ${{ github.event.inputs.targetbom }}
          COMMON_Branch: ${{ github.event.inputs.COMMONBranch }}
          CLEANTP: False
          DIEINDICATOR: CPU
