name: TPBuild_FM

env:
  CustomPath: "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe"
  
on:
  workflow_dispatch: 
    inputs:

      YmlRevision:
        type: boolean
        description: "Rev0"
        default: true
        
      BOMGroups:
        description: 'Target BOMGroups to build out'
        # Default value if no value is explicitly provided
        default: 'Class_NVL_S28C'
        # Input has to be provided for the workflow to run
        required: true
        
      name:
        description: 'MV_json_file or FULL (Dielet TP)'
        # Default value if no value is explicitly provided
        default: 'FULL'
        # Input has to be provided for the workflow to run
        required: true
        
      destination:
        description: 'I:\ drive destination'
        # Default value if no value is explicitly provided
        default: 'I:\'
        # Input has to be provided for the workflow to run
        required: true
      COMMONBranch:
        description: 'CommonBranchname|tag|sha|main'
        # Default value if no value is explicitly provided
        default: 'main'
        # Input has to be provided for the workflow to run
        required: true

      repjson:
        description: 'replace_for_mv_json_file_name'
        # Default value if no value is explicitly provided
        default: 'None'
        # Input has to be provided for the workflow to run
        required: true

      cleantp:
        type: boolean
        description: 'Clean TP Enable. Default is true'
        default: true

      acpy:
        description: 'TPSwitch or ACPY:'
        default: 'None'
        required: false

      previousTP:
        description: 'For TPI: Enter previous TP to generate report. eg: 21F0A'
        # Default value if no value is explicitly provided
        default: 'None'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  TP_BUILD:
    runs-on: [self-hosted, checkers_FM]

    steps:
    - name: Log Inputs
      run: echo "${{ toJSON(github.event.inputs) }}"

    - name: repo_init_check
      continue-on-error: true
      run: python -u I:/tpvalidation/engtools/tptools/mtl/beta/gen1/main/tprobot.py REPO_INIT main

    - uses: actions/checkout@v6
      with: 
        fetch-depth: 0
        clean: true              # remove untracked files before checkout
        ref: ${{ github.event.pull_request.head.ref }}
       
    - name: Checkout submodules
      run: |
        git submodule sync --recursive
        git submodule update --init --recursive --force

    - name: TP Build
      run:
          python -u I:/tpvalidation/engtools/tptools/mtl/beta/gen1/main/nvl_buildtp.py ${{ github.event.inputs.BOMGroups }} -flow -output ${{ github.event.inputs.destination }}
      env:
          PREVIOUSTP: ${{ github.event.inputs.previousTP }}
          COMMON_Branch: ${{ github.event.inputs.COMMONBranch }}
          REPJSON: ${{ github.event.inputs.repjson }}
          IN1: ${{ github.event.inputs.name }}
          CLEANTP: ${{ github.event.inputs.cleantp }}
          ACPY: ${{ github.event.inputs.acpy }}
          DIEINDICATOR: CPU
          CURRENT_BRANCH: ${{ github.ref_name }}
          DEST: ${{ github.event.inputs.destination }}
          
#    - name: Unused Report
#      run: python -u I:/tpvalidation/engtools/tptools/mtl/beta/gen1/main/tprobot.py UNUSED ${{ github.event.inputs.destination }}
#      continue-on-error: true
